### ISSUE TITLE
Thing для ID UNKNOW после добавления

### ISSUE THREAD

**Issue by LazyGatto** [d51x/org.openhab.binding.pandoracaralarmsystem#1]
Приветствую ;)
Попробовал добавить для своей машины. Бридж добавился вроде, без проблем.
Но вот когда пытаюсь добавить thing для машины с конкретным ID - он становится в статус UNKNOW.
В логах вот такая ошибка появляется.
```
2023-12-26 00:08:42.362 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected a long but was 34779.49595005275 at line 1 column 481 path $.mileage
	at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:333) ~[?:?]
	at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:323) ~[?:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212) ~[?:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433) ~[?:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393) ~[?:?]
	at com.google.gson.Gson.fromJson(Gson.java:1227) ~[?:?]
	at com.google.gson.Gson.fromJson(Gson.java:1137) ~[?:?]
	at com.google.gson.Gson.fromJson(Gson.java:1047) ~[?:?]
	at com.google.gson.Gson.fromJson(Gson.java:982) ~[?:?]
	at org.openhab.binding.pandoracaralarmsystem.internal.handlers.PandoraCarAlarmSystemBridgeHandler.lambda$3(PandoraCarAlarmSystemBridgeHandler.java:303) ~[?:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at org.openhab.binding.pandoracaralarmsystem.internal.handlers.PandoraCarAlarmSystemBridgeHandler.updateStats(PandoraCarAlarmSystemBridgeHandler.java:296) ~[?:?]
	at org.openhab.binding.pandoracaralarmsystem.internal.api.PandoraApiImpl.update(PandoraApiImpl.java:174) ~[?:?]
	at org.openhab.binding.pandoracaralarmsystem.internal.api.PandoraApiImpl.initialize(PandoraApiImpl.java:152) ~[?:?]
	at org.openhab.binding.pandoracaralarmsystem.internal.handlers.PandoraCarAlarmSystemBridgeHandler.pollState(PandoraCarAlarmSystemBridgeHandler.java:209) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.NumberFormatException: Expected a long but was 34779.49595005275 at line 1 column 481 path $.mileage
	at com.google.gson.stream.JsonReader.nextLong(JsonReader.java:980) ~[?:?]
	at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:331) ~[?:?]
	... 20 more
```

**Comment by d51x** [comment]
А что это за значение 34779.49595005275 может быть? За что отвечает? Случаем, не пробег?

**Comment by d51x** [comment]
да, это пробег 
Expected a long but was 34779.49595005275 at line 1 column 481 path $.**mileage**

**Comment by d51x** [comment]
fixed in 064bc7825020704e97dd44625167df4ef67f03c8
